// swift-tools-version:5.6
import PackageDescription

let package = Package(
    name: "Texture",
    platforms: [
        .iOS(.v14),
        .tvOS(.v14),
    ],
    products: [
        .library(name: "AsyncDisplayKit", type: .static, targets: ["AsyncDisplayKit"]),
    ],
    dependencies: [
        // PINRemoteImage support is enabled automatically once its headers are
        // visible, via `__has_include` in Source/Base/ASAvailability.h
        // (mirrors the podspec's default PINRemoteImage subspec).
        .package(url: "https://github.com/pinterest/PINRemoteImage.git", from: "3.0.0"),
    ],
    targets: [
        .target(
            name: "AsyncDisplayKit",
            dependencies: [
                .product(name: "PINRemoteImage", package: "PINRemoteImage"),
            ],
            path: "Source",
            exclude: [
                "AsyncDisplayKit.modulemap",
                "Info.plist",
            ],
            // Source/include/ holds the module headers (generated by
            // Scripts/generate-spm-headers.py): an umbrella copy with
            // framework-style imports plus a flat AsyncDisplayKit/ copy of
            // every header it reaches. The copies must never resolve by flat
            // basename during target compilation, or originals and copies
            // would get mixed within one translation unit.
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("Base"),
                .headerSearchPath("Debug"),
                .headerSearchPath("Details"),
                .headerSearchPath("Details/Transactions"),
                .headerSearchPath("Layout"),
                .headerSearchPath("Private"),
                .headerSearchPath("Private/Layout"),
                .headerSearchPath("TextExperiment/Component"),
                .headerSearchPath("TextExperiment/String"),
                .headerSearchPath("TextExperiment/Utility"),
                .headerSearchPath("TextKit"),
                .headerSearchPath("tvOS"),
                // Mirror the podspec's default subspecs. IGListKit and Yoga
                // stay opt-in like their subspecs; PINRemoteImage enables
                // itself via __has_include.
                .define("AS_USE_VIDEO", to: "1"),
                .define("AS_USE_MAPKIT", to: "1"),
                .define("AS_USE_PHOTOS", to: "1"),
                // Matches the podspec, where the AssetsLibrary subspec is
                // iOS-only: the framework does not exist in the tvOS SDK.
                .define("AS_USE_ASSETS_LIBRARY", to: "1", .when(platforms: [.iOS])),
            ],
            // Mirrors the podspec's `frameworks` for the default subspecs;
            // SwiftPM passes these when linking the final executable of a
            // package that depends on the static AsyncDisplayKit product.
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("MapKit"),
                .linkedFramework("Photos"),
                .linkedFramework("AssetsLibrary", .when(platforms: [.iOS])),
            ]
        ),
    ],
    cLanguageStandard: .c11,
    cxxLanguageStandard: .cxx11
)
